### PR TITLE
Corrected the style for search scrollbar

### PR DESCRIPTION
**Pull request by bjedrzejewski**

### CODE REVIEW

**Comment by owennw** [comment]
Hm I didn't notice this. Are these numbers random or coupled to something else? Can we start using variable/mixins to make this nicer and prevent future problems?

**Comment by bjedrzejewski** [comment]
At the moment this is to keep it in line with the design, this number is not present anywhere else other than fav tab (but this is coincidence possibly).

**Comment by bjedrzejewski** [comment]
I was thinking about using- @toolbar-height, but I am not sure if we have a guarantee that this is conceptually linked.

**Comment by owennw** [comment]
So it's not a calculated number based on other heights or something like that?

**Comment by bjedrzejewski** [comment]
It can be made into calculated number by refactoring the way the other stuff (search bar) is written. This is a separate refactoring though.

**Comment by bjedrzejewski** [comment]
@owennw changed it. Once travis is happy, can merge.

**Pull request merged**
