### PR TITLE
Make github link more visible

### LINKED ISSUE #575: Need a more prominent link to GitHub

### PR DESCRIPTION
**Pull request by bjedrzejewski**
Closes #575 as per @rmarcalo sucestion

### CODE REVIEW

**Comment by bjedrzejewski** [comment]
@rmarcalo is this ok?:

image

**Comment by owennw** [comment]
and @ColinEberhardt

**Comment by rmarcalo** [comment]
In my opinion this is clear enough without being intrusive and drawing too much attention.

**Comment by ColinEberhardt** [comment]
I'd like to consider adding the logo as well ... see https://github.com/ScottLogic/StockFlux/issues/575#issuecomment-194795916

**Pull request merged**
