### PR TITLE
test: add initial test for root reducer

### PR DESCRIPTION
**Pull request by jleft**

### CODE REVIEW

**Comment by jdhodges** [comment]
This doesn't work as is due to https://github.com/ScottLogic/StockFlux/pull/826 not being added yet. Will this commit be pushed onto the top of `react_redux` if merged or will it require rebasing?

**Comment by jleft** [comment]
> This doesn't work as is due to #826 not being added yet. Will this commit be pushed onto the top of react_redux if merged or will it require rebasing?

#826 has already been merged and the build has passed - unless I'm missing something?

**Comment by jdhodges** [comment]
Yes it has indeed been merged, just wondering if merging this will automatically push the changes on top of #826 or whether it needs rebasing (like we have to do on BitFlux).

**Comment by jleft** [comment]
Yes, merging will place the merge commit (if merged via _creating a merge commit_) or commit (if merged via _squash and merge_) on top of #826 (8cc1af641c541a16d9391a36587f2532ac7e625f). As we don't rewrite history in our main/shared branches (master, develop, react_redux etc.), this would be done for any PR.

Evidence of this is that the CI build is passing - the CI builds the merge of this feature branch and the base branch (react_redux in this case) - if it wasn't on top of #826, then the build would be failing.

The main reason we rebase PRs in BitFlux is because we get much cleaner commit history (as we use merge commits), it's not actually necessary to rebase to perform the merge, unless there are conflicts (then rebase or merge would be required).

As we're using  _squash and merge_ in StockFlux, there's no need to rebase to generate nicer history; this would only be needed to be to resolve conflicts.

https://github.com/blog/2141-squash-your-commits

**Comment by jdhodges** [comment]
Awesome, thanks for explaining this @jleft - makes much more sense now :)

**Comment by jleft** [comment]
No problem - pleased it helped - it is fairly confusing! Give me a shout if it'd be helpful to go through any of this in more detail :smile:

**Pull request merged**
