### PR TITLE
Replace SVGs with PNG images

### PR DESCRIPTION
**Pull request by owennw**
Towards #419, don't know if this is sufficient to close it though.

### CODE REVIEW

**Comment by WPFerg** [comment]
I think the ones done are good, but I think #419 also needs the Bitflux icons updated, too. I'm happy to merge this one in, though

**Comment by bjedrzejewski** [comment]
@owennw we can't merge this yet. For example the start icon png is 15px, but we are forcing it to render as 16px. This brings back the sub-optimal rendering problem. Is it the css problem, or icon png should be larger? There are issues like that with most icons (magnifying glass and star on the top) etc.

**Comment by owennw** [comment]
Working on it. I also think I've lost the closed tabs icon in compact view..

**Comment by bjedrzejewski** [comment]
@owennw did Rui give you updated pngs?

**Pull request merged**
